name: Build executable with Nuitka
on: [push]

jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Github Checkout
        uses: actions/checkout@v4

      - name: Setting Up Environment
        uses: actions/setup-python@v5
        with:
          python-version: '3.14'

      - name: Compile with Nuitka
        uses: Nuitka/Nuitka-Action@main
        with:
          nuitka-version: main
          script-name: main.py
          mode: standalone
          onefile: true
          
      - name: Uploading artifact
        uses: actions/upload-artifact@v4
        with:
          name: build-output
          path: build/*.exe
